# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Results(object):
    def setupUi(self, Results):
        Results.setObjectName("Results")
        Results.resize(480, 471)
        self.label = QtWidgets.QLabel(Results)
        self.label.setGeometry(QtCore.QRect(30, 20, 261, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Results)
        self.lineEdit.setGeometry(QtCore.QRect(310, 20, 113, 22))
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Results)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 290, 16))
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(Results)
        self.tableWidget.setGeometry(QtCore.QRect(30, 120, 411, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.dict_sort

        self.loaddata(self.dict_sort)

        self.retranslateUi(Results)
        QtCore.QMetaObject.connectSlotsByName(Results)

    def retranslateUi(self, Results):
        _translate = QtCore.QCoreApplication.translate
        Results.setWindowTitle(_translate("Results", "Dialog"))
        self.label.setText(_translate("Results", "Системой идентифицирован пользователь:"))
        self.label_2.setText(_translate("Results", f"Оценка:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Results", "Логин"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Results", "Расстояние"))


    def loaddata(self, dict_sort):
        # people = [{"Номер": "1", "Логин": 'eac23', 'Расстояние': "101"}]
        # people = {'eac23': 67.10368240683194, 'lrd1': 115.57190983486902, 'ksk12': 117.21063081690606, 'avo19': 123.18892032246849, 'nvb16': 139.9711310547301, 'vve15': 158.97610543749013}
        row = 0
        self.tableWidget.setRowCount(len(dict_sort))
        for person in dict_sort:
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(person))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(dict_sort[person])))
            row += 1


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Results = QtWidgets.QDialog()
    ui = Ui_Results()
    ui.setupUi(Results)
    Results.show()
    sys.exit(app.exec_())
